note/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "note"

urlpatterns = [
    path('mynotes/', views.mynotes, name = "mynotes"),
    path('addnote/', views.addnote, name = "addnote"),
    path('note/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateNote, name = "update"),
    path('delete/<int:id>', views.deleteNote, name = "delete"),
    path('', views.notes, name = "notes"),
]

studentstudyportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = "index"),
    path('user/',include("user.urls")),

    #notes
    path('notes/', include("note.urls")),

    #homeworks
    path('homeworks/',views.homeworks, name = "homeworks"),
    path('update_homeworks/<int:pk>',views.update_homeworks,name="update-homeworks"),
    path('delete_homeworks/<int:pk>',views.delete_homeworks,name="delete-homeworks"),
    
    #exammarks
    path('exammarks/',views.exammarks, name = "exammarks"),
    path('update_exammarks/<int:pk>',views.update_exammarks,name="update-exammarks"),
    path('delete_exammarks/<int:pk>',views.delete_exammarks,name="delete-exammarks"),

    #examcalendar
    path('examcalendar/',views.examcalendar, name = "examcalendar"),
    path('update_calendar/<int:pk>',views.update_examcalendar,name="update-examcalendar"),
    path('delete_calendar/<int:pk>',views.delete_examcalendar,name="delete-examcalendar"),

    #todolist
    path('todolist/',views.todolist, name = "todolist"),
    path('update_todo/<int:pk>',views.update_todo,name="update-todo"),
    path('delete_todo/<int:pk>',views.delete_todo,name="delete-todo"),

    #timer
    path('timer/',views.timer, name = "timer"),

    #askquestion
    path('questions/',views.questions, name = "questions"),
    path('askquestion/',views.askquestion, name = "askquestion"),
    path('question_detail/<int:id>',views.question_detail, name = "question_detail"),
    path('question_delete/<int:id>',views.question_delete, name = "question_delete"),
    path('comment/<int:id>',views.addComment, name = "comment"),
    

    #music
    path('music/',views.music, name = "music"),

        
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
]

templates/includes/navbar.html
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse fixed-top">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">DERSLİK PORTALI</a>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        

        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:logout' %}">Çıkış Yap</a>
            </li> 
          {% else %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'user:login' %}">Giriş Yap</a>
            </li>
            <li class="nav-item active">
             <a class="nav-link" href="{% url 'user:register' %}">Kayıt Ol</a>
            </li> 
          {% endif %}

   
        </ul>
      
      </div>
    </nav>
    
    