note/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "note"

urlpatterns = [
    path('mynotes/', views.mynotes, name = "mynotes"),
    path('addnote/', views.addnote, name = "addnote"),
    path('note/<int:id>', views.detail, name = "detail"),
    path('update/<int:id>', views.updateNote, name = "update"),
    path('delete/<int:id>', views.deleteNote, name = "delete"),
    path('', views.notes, name = "notes"),
]

studentstudyportal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from dashboard import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index, name = "index"),
    path('user/',include("user.urls")),

    #notes
    path('notes/', include("note.urls")),

    #homeworks
    path('homeworks/',views.homeworks, name = "homeworks"),
    path('update_homeworks/<int:pk>',views.update_homeworks,name="update-homeworks"),
    path('delete_homeworks/<int:pk>',views.delete_homeworks,name="delete-homeworks"),
    
    #exammarks
    path('exammarks/',views.exammarks, name = "exammarks"),
    path('update_exammarks/<int:pk>',views.update_exammarks,name="update-exammarks"),
    path('delete_exammarks/<int:pk>',views.delete_exammarks,name="delete-exammarks"),

    #examcalendar
    path('examcalendar/',views.examcalendar, name = "examcalendar"),
    path('update_calendar/<int:pk>',views.update_examcalendar,name="update-examcalendar"),
    path('delete_calendar/<int:pk>',views.delete_examcalendar,name="delete-examcalendar"),

    #todolist
    path('todolist/',views.todolist, name = "todolist"),
    path('update_todo/<int:pk>',views.update_todo,name="update-todo"),
    path('delete_todo/<int:pk>',views.delete_todo,name="delete-todo"),

    #timer
    path('timer/',views.timer, name = "timer"),

    #askquestion
    path('questions/',views.questions, name = "questions"),
    path('askquestion/',views.askquestion, name = "askquestion"),
    path('question_detail/<int:id>',views.question_detail, name = "question_detail"),
    path('question_delete/<int:id>',views.question_delete, name = "question_delete"),
    path('comment/<int:id>',views.addComment, name = "comment"),
    

    #music
    path('music/',views.music, name = "music"),

        
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

note/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
class Note(models.Model):
    author = models.ForeignKey("auth.User", on_delete = models.CASCADE)
    title = models.CharField(max_length = 50, verbose_name = "Başlık")
    content = RichTextField(verbose_name = "İçerik")
    created_date = models.DateTimeField(auto_now_add = True, verbose_name = "Oluşturulma Tarihi")
    note_image = models.FileField(blank = True, null = True, verbose_name = "Fotoğraf Ekle")
    def __str__(self):
        return self.title

note/forms.py
from django import forms
from .models import Note

class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ["title", "content", "note_image"]

note/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from .forms import NoteForm
from .models import Note
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Create your views here.

def notes(request):
    keyword = request.GET.get("keyword")
    if keyword:
        notes = Note.objects.filter(title__contains = keyword)
        return render(request, "notes.html", {"notes" : notes})
    notes = Note.objects.filter(author = request.user)
    return render(request, "notes.html", {"notes" : notes})

def index(request):
    return render(request,"index.html")

@login_required(login_url = "user:login")
def mynotes(request):
    notes = Note.objects.filter(author = request.user)
    context = {
        "notes" : notes
    }
    return render(request, "mynotes.html", context)

@login_required(login_url = "user:login")
def addnote(request):
    form = NoteForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        note = form.save(commit = False)
        note.author = request.user
        note.save()
        messages.success(request, "Not başarıyla eklendi.")
        return redirect("note:mynotes")

    context = {
        "form" : form
    }
    return render(request, "addnote.html", context)

@login_required(login_url = "user:login")
def detail(request, id):
    note = get_object_or_404(Note, id = id)
    return render(request, "detail.html", {"note":note})

@login_required(login_url = "user:login")
def updateNote(request, id):
    note = get_object_or_404(Note, id = id)
    form = NoteForm(request.POST or None or request.FILES or None, instance = note)
    if form.is_valid():
        note = form.save(commit = False)
        note.author = request.user
        note.save()
        messages.success(request, "Not başarıyla güncellendi.")
        return redirect("note:mynotes")
    return render(request, "update.html", {"form" : form})

@login_required(login_url = "user:login")
def deleteNote(request, id):
    note = get_object_or_404(Note, id = id)
    note.delete()
    messages.success(request, "Not başarıyla silindi.")
    return redirect("note:mynotes")

templates/exammarks.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<style>
body{
    background-color: #7C7FE4;
}
</style>
<div class="container" style="margin-bottom:120px">
    <h3>Sınav Notları</h3>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type = "submit" class = "btn btn-danger">Sınav Notu Ekle</button>
    </form>
    <hr>
    <br>

    {% if not isthereexam %}
    <table class="table table-striped table-bordered table-hover" style="background-color: #F5F0F0; ">
    <caption style="color:#2B2B2B">Sınav Notları</caption>
    <thead class="table-dark">
        <tr >
        <th scope="col" style="width:5%">Id</th>
        <th scope="col" style="width:15%">Ders</th>
        <th scope="col" style="width:9%">Birinci Vize</th>
        <th scope="col" style="width:9%">İkinci Vize</th>
        <th scope="col" style="width:9%">Final</th>
        <th scope="col" style="width:47%">Ortalama</th>
        <th scope="col" style="width:3%">Güncelle</th>
        <th scope="col" style="width:3%">Sil</th>
        </tr>
    </thead>
    <tbody>
        {% for exammark in exammarks %}
            
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{exammark.subject}}</td>
            <td>{{exammark.firstExam}}</td>
            <td>{{exammark.secondExam}}</td>
            <td>{{exammark.final}}</td>
            <td>
            {% if exammark.average <= 40 %}
            <div class="progress">
                <div class="progress-bar bg-danger" role="progressbar" style="width: {{exammark.average}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            {% else %}
            <div class="progress">
                <div class="progress-bar bg-success" role="progressbar" style="width: {{exammark.average}}%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>
            {% endif %}
            </td>
            <td><a href="{% url 'update-exammarks' exammark.id %}"><i class="far fa-edit" style="color:rgb(203,11,11); margin-left:30px"></i></a></td>
            <td><a href="{% url 'delete-exammarks' exammark.id %}"><i class="fa fa-trash icon-cog" style="color:rgb(203,11,11)" ></i></a></td>
            </tr>
            
        {% endfor %}
    </tbody>
    </table>
    {% else %}
    <div class = "alert alert-danger">Sınav notunuz bulunmuyor.</div>
    {% endif %}
</div>

{% endblock body %}

templates/homeworks.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}


{% block body %}
<style>
body{
    background-color: coral;
}
</style>
<div class="container" style="margin-bottom:120px">
    <h3>Ödevler</h3>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        
        <button type = "submit" class = "btn btn-danger">Ödev Ekle</button>
    </form>
    
    <hr>
    <br>

    {% if notFinishedNumber > 0%}
    <table class="table table-striped table-hover table-bordered" style="background-color: #F5F0F0; ">
    <caption style="color:#2B2B2B">Ödevler</caption>
    <thead class="table-dark">
        <tr >
        <th scope="col" style="width:5%">Id</th>
        <th scope="col" style="width:17%">Ders</th>
        <th scope="col" style="width:50%">İçerik</th>
        <th scope="col" style="width:20%">Son Tarih</th>
        <th scope="col" style="width:5%"></th>
        <th scope="col" style="width:3%">Sil</th>
        </tr>
    </thead>
    <tbody>
        {% for homework in homeworks %}
            {% if homework.is_finished == False %}
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{homework.subject}}</td>
            <td>{{homework.description}}</td>
            <td>{{homework.due}}</td>
            <td style="margin-left:50px">
            <a href="{% url 'update-homeworks' homework.id %}">
                <div class="form-check container-fluid" style="margin-left:28px">
                {% if homework.is_finished == True %}
                <input class="form-check-input " type="checkbox" value="" id="flexCheckDefault"  checked>
                {% else %}
                <input class="form-check-input " type="checkbox" value="" id="flexCheckDefault">
                {% endif %}
                </div>
            </a>
            </td>
            <td><a href="{% url 'delete-homeworks' homework.id %}"><i class="fa fa-trash icon-cog" style="color:rgb(203,11,11)" ></i></a></td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
    </table>
    {% else %}
    <div class = "alert alert-danger">Ödeviniz bulunmuyor.</div>
    {% endif %}

    <hr>
    <br>

    {% if finishedNumber > 0 %}
    <table class="table table-striped table-bordered table-hover" style="background-color: #F5F0F0;">
    <caption style="color:#2B2B2B">Tamamlanan Ödevler</caption>
    <thead class="table-dark">
        <tr >
        <th scope="col" style="width:5%">Id</th>
        <th scope="col" style="width:17%">Ders</th>
        <th scope="col" style="width:50%">İçerik</th>
        <th scope="col" style="width:20%">Son Tarih</th>
        <th scope="col" style="width:5%"></th>
        <th scope="col" style="width:3%">Sil</th>
        </tr>
    </thead>
    <tbody>
        {% for homework in homeworks %}
            {% if homework.is_finished == True %}
            <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td><s>{{homework.subject}}</s></td>
            <td><s>{{homework.description}}</s></td>
            <td><s>{{homework.due}}</s></td>
            <td style="margin-left:50px">
            <a href="{% url 'update-homeworks' homework.id %}">
                <div class="form-check container-fluid" style="margin-left:28px">
                {% if homework.is_finished == True %}
                <input class="form-check-input " type="checkbox" value="" id="flexCheckDefault"  checked>
                {% else %}
                <input class="form-check-input " type="checkbox" value="" id="flexCheckDefault">
                {% endif %}
                </div>
            </a>
            </td>
            <td><a href="{% url 'delete-homeworks' homework.id %}"><i class="fa fa-trash icon-cog" style="color:rgb(203,11,11)" ></i></a></td>
            </tr>
            {% endif %}
        {% endfor %}
    </tbody>
    </table>
    {% else %}
    <div class = "alert alert-danger">Tamamlanan ödeviniz bulunmuyor.</div>
    {% endif %}

</div>
{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% load static %}
{% block body %}
<style>
body{
    background-color: #DECDE7;
}
</style>

<div class="row justify-content-md-center">

    <div class="card col-2 ">
        <br>
            <img class="card-img-top" src="{% static 'images/takingnotes1.jpg' %}" alt="Notes image" >
        <br>
        <div class="card-body ">
        <a class="nav-link" href="{% url 'note:mynotes' %}">
            <h5 class="card-title">Notlar</h5>
            <p class="card-text">Ders çalışırken aldığınız notları saklayabilirsiniz.</p>
            <br>
        </a>
        </div>
    </div>

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/homeworks.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'homeworks' %}">
                <h5 class="card-title">Ödevler</h5>
                <p class="card-text">Ödev takibini daha kolay yapmak için ödevlerinizi ve teslim tarihlerinizi listeye ekleyebilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/examnotes.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'exammarks' %}">
                <h5 class="card-title">Sınav Notları</h5>
                <p class="card-text">Sınavlardan aldığınız notları ekleyebilir ve dersi başarıyla geçmek için diğer sınavlardan kaç almanız gerektiğini hesaplayabilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/calendar.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'examcalendar' %}">
                <h5 class="card-title">Sınav Takvimi</h5>
                <p class="card-text">Sınav takibini daha kolay yapmak için program oluşturabilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

</div>

<div class="row justify-content-md-center" style="margin-bottom:100px">

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/todoo.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'todolist' %}">
                <h5 class="card-title">Yapılacaklar Listesi</h5>
                <p class="card-text">Günlük, haftalık yapmayı planladığınız işlerin takibini kolaylaştırmak için maddelerinizi yapılacaklar listesine ekleyebilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/timer.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'timer' %}">
                <h5 class="card-title">Kronometre</h5>
                <p class="card-text">Süre tutarak ders çalışırsanız odağınızı arttırabilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/questions.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'questions' %}">
                <h5 class="card-title">Soru - Cevap</h5>
                <p class="card-text">Merak ettiklerinizi sorup cevaplarını bulabilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

    <div class="card col-2">
        <br>
        <img class="card-img-top" src="{% static 'images/music.jpg' %}" alt="Notes image">
        <br>
        <div class="card-body">
            <a class="nav-link" href="{% url 'music' %}">
                <h5 class="card-title">Ders Çalışma Müziği</h5>
                <p class="card-text">Ders çalışırken konsantrasyonunuzu arttıracak çalma listesini dinleyebilirsiniz.</p>
                <br>
            </a>
        </div>
    </div>

</div>




{% endblock body %}

templates/layout.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href='styles.css?version=1' rel='stylesheet'>
    <link rel="stylesheet" type="text/css" href="styles.css?version=51">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <title>DERSLİK PORTALI</title>
</head>
<body>
    

    {% include "includes/navbar.html" %}

    <div style="margin-top=100px" class="container-fluid">
        <br><br><br>
        {% if messages %}
            {% for message in messages %}
                {% if message.tags == "info" %}
                <div class="alert alert-danger">{{ message }}</div>
                {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endif %}
            {% endfor %}
        {% endif %}

        {% block body %}
        
        {% endblock body %}
    
    
    </div>
    
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
<style>
body{
    background-color: #DECDE7;
}
</style>
<div class="row">
  <div class="col-md-6 offset-md-3">
    <br><br><br><br>
    <h3>Giriş Yap</h3>
    <hr>
    <form method = "post">
      {% csrf_token %}
      {{form|crispy}}
      <button type = "submit" class = "btn btn-danger">Giriş Yap</button>
    </form>
  </div>  
</div>

{% endblock body %}

templates/music.html
{% extends "layout.html" %}

{% block body %}
<style>
 body  {
    background-color: #D98880;
 }
</style>


<div class="col-md-8 offset-md-2">
    <br><br>
    <h3>Çalma Listeleri</h3>
    <hr>
    <br>
    
    <h5>Başarıya Giden Notalar</h5>
    <hr>
    <iframe src="https://open.spotify.com/embed/playlist/0BMV2U3bS3cgjGk54zvFnV?utm_source=generator&theme=0" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
    <br><br><br>

    <h5>Maksimum Konsantrasyon</h5>
    <hr>
    <iframe src="https://open.spotify.com/embed/playlist/37i9dQZF1DX50uBtloazYo?utm_source=generator&theme=0" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
    <br><br><br>

    <h5>Klasik Müzik</h5>
    <hr>
    <iframe src="https://open.spotify.com/embed/playlist/1h0CEZCm6IbFTbxThn6Xcs?utm_source=generator&theme=0" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
    <br><br><br>    
    
    <h5>Piyano</h5>
    <hr>
    <iframe src="https://open.spotify.com/embed/playlist/2q7U9Dh7buTnrwHEWxcxiq?utm_source=generator&theme=0" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
    <br><br><br>

    <h5>Enerjik 90lar</h5>
    <hr>
    <iframe src="https://open.spotify.com/embed/album/4ZBTZtl0jjtrGMgNwxqMQE?utm_source=generator&theme=0" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
    <br><br><br>

    <h5>Enerjik 2000ler</h5>
    <hr>
    <iframe src="https://open.spotify.com/embed/playlist/37i9dQZF1DWYteTcNVQZNq?utm_source=generator&theme=0" width="100%" height="380" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>
</div>
<br><br><br>
{% endblock body %}

templates/mynotes.html
{% extends "layout.html" %}

{% block body %}
<style>
 body  {
    background-color: #AED6F1;
 }
</style>

<div class="container" >
<br><br><br><br>
<h3 style="text-align:left">Notlarım</h3>

<hr>

{% if request.user.is_authenticated %}
    <a href = "/notes/addnote" class = "btn btn-danger">Not Ekle</a>
    <a href = "/notes" class = "btn btn-danger">Detaylarıyla Notlar</a>
    <br><br>

    {% if notes %}

        <table class="table table-hover table-striped table-bordered" style="background-color: #F5F0F0; ">
            <thead>
            <tr>
                <th scope="col">Not</th>
                <th scope="col">Oluşturulma Tarihi</th>
                <th scope="col">Güncelle</th>
                <th scope="col">Sil</th>
            </tr>
            </thead>
            <tbody>
                {% for note in notes %}
                
                    <tr>
                        <td><a href = "{% url 'note:detail' note.id %}">{{note.title}}</a></td>
                        <td >{{note.created_date}}</td>
                        <td ><a href = "{% url 'note:update' note.id %}" type="button" class="btn btn-danger">Güncelle</a></td>
                        <td ><a href = "{% url 'note:delete' note.id %}" type="button" class="btn btn-danger">Sil</a></td>

                    </tr>

                {% endfor %}    
            </tbody>
        </table>

    {% else %}
        <div class = "alert alert-danger">Henüz makaleniz bulunmuyor.</div>
    {% endif %}

{% else %}
    <div class="alert alert-warning" role="alert">
        Not ekleyebilmek için kullanıcı girişi yapınız.
    </div>
{% endif %}
</div>
{% endblock body %}

templates/question_detail.html
{% extends "layout.html" %}


{% block body %}
<style>
 body  {
    background-color: #EEADDE;
 }
</style>

<div class="row">
    <div class="col-md-7 offset-md-3">
        <h2>Soru Detayı</h2>
        <hr> 
            <div class="card">
            <div class="card-header">
               <h3 class="fw-bolder mb-1">{{question.title}}</h3>
            </div>
            <div class="card-body" style="margin-left:18px">
            <br>
                <p class="card-text">{{question.content|safe}}</p>
            <br>
            </div>
            <div class="card-footer">
                <small class="text-muted" >Oluşturulma Tarihi: {{question.created_date}}</small>
                <br>
                <small class="text-muted">{{question.author.username}} tarafından soruldu.</small>
            </div>
            </div>
            <br>
            <a href = "/questions" type="button" class="btn btn-danger" style="margin-left:40px">Geri Dön</a>
    </div>
    <hr>   
</div>
<div class="row">
    <div class="col-md-7 offset-md-3">
        
        <br>
        <hr>

        <h2>Yorumlar</h2>
        <hr>
        {% if comments %}
            {% for comment in comments  %}
                <div class="card" style="margin-left:18px">
                <div class="card-header">
                <h3 class="fw-bolder mb-1">{{comment.comment_author}}</h3>
                </div>
                <div class="card-body" style="margin-left:18px">
                <br>
                    <p class="card-text">{{comment.comment_content}}</p>
                <br>
                </div>
                <div class="card-footer">
                    <small class="text-muted">{{comment.comment_date}}</small>
                </div>
                </div>

            {% endfor %}
        {% else %}
        <div class = "alert alert-warning">
            Bu soruya henüz cevap verilmedi.
        </div>
        {% endif %}

        <div class="card my-4" style="background: transparent">
            <h5 class="card-header" style="background: transparent">Soruyu cevapla:</h5>
            <div class="card-body">
                <form method = "post" action = "/comment/{{question.id}}">
                    {% csrf_token %}    
                    <div class="form-group" style="margin-left:10px; margin-right:10px">
                        <label for="formGroupExampleInput">İsim</label>
                        <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="İsminizi girin">
                    </div>
                    <div class="form-group" style="margin-left:10px; margin-right:10px">
                        <label for="formGroupExampleInput">Cevap</label>
                        <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Cevapla</button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock body %}

templates/questions.html
{% extends "layout.html" %}

{% block body %}
<style>
 body  {
    background-color: #EEADDE;
 }
</style>
<div class="container" >
<h3 style="text-align:left">Sorular</h3>
<hr>
<a href = "{% url 'askquestion' %}" class = "btn btn-danger float-right">Soru Sor</a>

<form>
    {% csrf_token %}
    <input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Ara...">
    <button type="submit" class="btn btn-danger">Ara</button>
</form>
<hr>
{% if questions %}

        <table class="table table-hover" style="background-color: #F5F0F0; ">
            <thead>
            <tr>
                <th scope="col">Soru</th>
                <th scope="col">Kullanıcı</th>
                <th scope="col">Oluşturulma Tarihi</th>
                <th scope="col">Sil</th>
            </tr>
            </thead>
            <tbody>
                {% for question in questions %}
                
                    <tr>
                        <td ><a href = "/question_detail/{{question.id}}">{{question.title}}</a></td>
                        <td >{{question.author}}</td>
                        <td >{{question.created_date}}</td>
                        <td ><a href = "{% url 'question_delete' question.id %}" type="button" class="btn btn-danger">Sil</a></td>
                    </tr>

                {% endfor %}    
            </tbody>
        </table>

    {% else %}
        <div class = "alert alert-danger">Soru bulunamadı.</div>
    {% endif %}


{% endblock body %}

templates/register.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<style>
body{
    background-color: #DECDE7;
}
</style>
<div class="row">
    <div class="col-md-6 offset-md-3">
        <br><br><br><br>
        <h3>Kayıt Ol</h3>
        <hr>       
        <form method = "post">
            {% csrf_token %}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Kayıt Ol</button>
        </form>
      </div>  
  </div>

{% endblock body %}

templates/update.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<style>
 body  {
    background-color: #AED6F1;
 }
</style>
<div class="row">
  <div class="col-md-6 offset-md-3">
  <br><br><br><br>
    <h3>Not Güncelle</h3>
    <hr>
    <form method = "post">
        {% csrf_token %}
        {{form.media}}
        {{form|crispy}}
        <button type = "submit" class = "btn btn-danger">Güncelle</button>
    </form>
    </div>  
</div>

{% endblock body %} 

templates/updateexammarks.html
{% extends "layout.html" %}
{% load crispy_forms_tags %}

{% block body %}
<style>
body{
    background-color: #7C7FE4;
}
</style>
<div class="container" style="margin-bottom:120px">
    <h3>Sınav Notları</h3>
    <hr>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type = "submit" class = "btn btn-danger">Güncelle</button>
    </form>
</div>

{% endblock body %}